### ISSUE TITLE
[did-client] Strip trailing "/" when loading DID server URL

### ISSUE THREAD

**Issue by tahpot** [verida/verida-js#106]
When specifying the DID Server endpoint, it must not have a trailing slash.

ie: `https://dids.testnet.verida.io:5001` not `https://dids.testnet.verida.io:5001/`.

This needs to be more robust by removing a trailing slash if it exist.

Update should be in did-client package.

**Comment by kalanamt** [comment]
Estimation :- 24 hrs

**Comment by tahpot** [comment]
This trailing slash issue also exists for all the server endpoints specified in DID documents.

When we retrieve a `serviceEndpoint` URL from a DID document, we should normalize the URL to have a trailing `/`.

**Comment by tahpot** [comment]
Closed with #136
