### ISSUE TITLE
[storage-link] Handle missing trailing "/" when specifying storage node URL

### ISSUE THREAD

**Issue by tahpot** [verida/verida-js#107]
When specifying the storage node URL for an account, it must have a trailing slash.

ie: `https://db.testnet.verida.io:5002/` not `https://db.testnet.verida.io:5002`.

This needs to be more robust by adding a trailing slash if it doesn't exist.

Update should be in `storage-link` package.

**Comment by kalanamt** [comment]
Estimation :- 24 hrs
