### ISSUE TITLE
Modify signature schema to be versionless

### ISSUE THREAD

**Issue by tahpot** [verida/verida-js#110]
See discussion here: https://github.com/verida/verida-js/issues/18#issuecomment-962565680

See [sign data method](https://github.com/verida/verida-js/blob/e3fb778c510a6f148013c32ee177fb3fe7476ae2/packages/client-ts/src/context/engines/verida/database/base-db.ts#L400) that generates the signatures.

Modify the signature scheme to retain the base schema URL, but drop all version information.

ie: Sign the data with `schema=https://common.schemas.verida.io/health/note` instead of `schema=https://common.schemas.verida.io/health/note/v0.1.0/schema.json`.

Need to also ensure the schema verification handles this correctly.

**Comment by tahpot** [comment]
An example of a current database record:

```
{
  name: 'Vitalik Buterin',
  firstName: 'Vitalik',
  lastName: 'Buterin',
  email: 'me@vitalik.eth',
  schema: 'https://common.schemas.verida.io/social/contact/v0.1.0/schema.json'
  signatures: {
    "did:vda:0xBd11fC481B4D02031C4D6DD0b06634b58Bd61146?context=0xaf6244520764353a17845861e771473f194889faa3d6e90565e353445dcc5245": '0x0f338d2b2917b04fbceda22162975bbe568e41e937f36b8d…a8b503eda094a64d40fe9012ecacd7755878f632af031bc1b'}
}
```

The `signature` is currently generated by hashing the core data of record (minus the signature, becuase it doesn't exist yet):


```
{
  name: 'Vitalik Buterin',
  firstName: 'Vitalik',
  lastName: 'Buterin',
  email: 'me@vitalik.eth',
  schema: 'https://common.schemas.verida.io/social/contact/v0.1.0/schema.json'
}
```

Let's assume that there is a future update to this schema to `v0.2.0`. In the future, we will likely support a way to migrate data from `v0.1.0` to `v0.2.0`:

```
{
  name: 'Vitalik Buterin',
  firstName: 'Vitalik',
  lastName: 'Buterin',
  email: 'me@vitalik.eth',
  schema: 'https://common.schemas.verida.io/social/contact/v0.2.0/schema.json'
}
```

However the existing `signature` will no longer be valid, because the schema string has changed. As such, we want the signature method to sign a modified, versionless data similar to this:

```
{
  name: 'Vitalik Buterin',
  firstName: 'Vitalik',
  lastName: 'Buterin',
  email: 'me@vitalik.eth',
  schema: 'https://common.schemas.verida.io/social/contact/schema.json'
}
```

The version part has been removed from the schema string (`v0.2.0`).

**Comment by kalanamt** [comment]
@tahpot
*  Is all data has the `schema` attribute as a JSON ? or is it an optional JSON attribute?
* Can data be in any format ? (JSON | raw | binary) or is it a `JSON` in  `protected async _signData(data: any)` ?

**Comment by kalanamt** [comment]
We need to have a strict analysis of schema name :- https://common.schemas.verida.io/health/note/v0.1.0/schema.json
Ensures the version always before the `https:/..................................../{version}/*.json`
Can use the [semvar](https://semver.org/) versioning as the standard.
