### ISSUE TITLE
[verifiable-credential]: Error in DID document 

### ISSUE THREAD

**Issue by cmcWebCode40** [verida/verida-js#113]
When I try to verify a credential using the `verifyCredential(vcJwt, resolver)`  method from  the  `did-jwt-vc` 

request URL : https://dids.testnet.verida.io:5001/load?did=did:vda:0x68fCc963f0B6057Bd48b2714F14B3305B81621b1

I get this error :
<img width="1080" alt="Screenshot 2021-12-08 at 06 39 03" src="https://user-images.githubusercontent.com/54280620/145155398-9d304e98-a252-4737-a2a2-7abea2a787ec.png">

## Steps to reproduce

```js
      import { Resolver } from 'did-resolver';
      import vdaResolver from '@verida/did-resolver';
      
      const DID_REGISTRY_ENDPOINT = 'https://dids.testnet.verida.io:5001';

     	async verifyCredential(vcJwt: string): Promise<void> {
		const resolver = this.getResolver();
		return verifyCredential(vcJwt, resolver);
	}

	getResolver(): any {
		const resolver = vdaResolver.getResolver(DID_REGISTRY_ENDPOINT);
		return new Resolver(resolver);
	}


```

**Comment by tahpot** [comment]
@cmcWebCode40 Can you please commit a unit test that causes this issue so I can replicate.

**Comment by cmcWebCode40** [comment]
Alright, i will do that

**Comment by tahpot** [comment]
@cmcWebCode40 Also, can you try changing your `alg` value to be `EcdsaSecp256k1VerificationKey2019` in your `credential.ts` file and see if that fixes your issue?

**Comment by cmcWebCode40** [comment]
@tahpot, I just completely wrote a test for verify credentials and it worked correctly, I will commit it now for you to have a look

**Comment by cmcWebCode40** [comment]
@tahpot, i have committed the tests into this branch here 
 https://github.com/verida/verida-js/tree/feature/112-credential-library

**Comment by tahpot** [comment]
@cmcWebCode40 Please have a look at my two most recent commits.

1. I moved the `generate URI` function into a new `client-ts:Utils` helper
2. I have modified the `generate URI` to `hash` the context name
3. There is a bug in your code with the database name not being set in the URI, so I added a failing unit test for you to fix

**Comment by cmcWebCode40** [comment]
Noted.

@tahpot since we using `openExternalDatastore()` that's requires a `schemaURI`  should replace the database name with the schema uri  ? 

code : https://github.com/verida/verida-js/blob/8322a1fb078ebabe38adf8a7d91598472a92ff55/packages/verifiable-credentials/src/credentials.ts#L140

**Comment by tahpot** [comment]
@cmcWebCode40 No, because the URI can only point to a database not a datastore.

You will need to fetch the database name from the schema and then use that.

**Comment by cmcWebCode40** [comment]
alright, thanks

**Comment by cmcWebCode40** [comment]
@tahpot , 

I have got two errors ATM

1 . When I try to open a datastore using the database name I have retrieved from a  schema URl 
 e.g `credential_public_encrypted` (https://common.schemas.verida.io/credential/public/encrypted/v0.1.0/schema.json)
 
 I get a `403` access denied error because its making a request to this URL  https://schemas.testnet.verida.io/credential_public_encrypted/schema.json
 
 
 2 .  When I try to fetch URI using the `fetchURI()` method I get this error  
 
 ```
     Error: Unable to locate requested storage context (0x42406d644c8e884be0f76ee05539cfba03eda65baa2bda33ecd364ce4d18047c) for this DID (did:vda:0xB3729982A2585544FD72c99CF3773a9c6baBD55c) -- Storage context doesn't exist (try force create?)
      at DIDContextManager.<anonymous> (/Users/chinweikemichael/Desktop/verida/verida-js/packages/client-ts/dist/did-context-manager.js:161:39)
      
  ```

**Comment by tahpot** [comment]
@cmcWebCode40 

1. You have this code:

```
const publicCredentials = await this.context.openDatastore(dbName, {
			permissions: options.permissions,
		});
```

You are opening a `datastore` with a database name. Datastores and databases are different. You need to use `context.openDatabase()` if you are opening a database.

2.

>When I try to fetch URI using the fetchURI() method I get this error

I have broken this for you with my new `generateUri` method. Let me have a think about this and get back to you. I'm trying to avoid having a URL with a plaintext context name (ie: `verida://<did>/Verida: Vault/<db name>/<row>`

3. The `sharing-credential` should focus on just sharing an existing credential object. The issuing should only live in the `credential` class. We want to avoid tight coupling.

**Comment by tahpot** [comment]
@cmcWebCode40 I've pushed a change that fixes the various issues. Please take a careful look at the changes.

**Comment by tahpot** [comment]
I'd still like you to resolve this design issue:

>The sharing-credential should focus on just sharing an existing credential object. The issuing should only live in the credential class. We want to avoid tight coupling.

**Comment by tahpot** [comment]
Also, `fetchURI` should also move into `client-ts::Utils`.

**Comment by cmcWebCode40** [comment]
> I'd still like you to resolve this design issue: 

Do you mean I should not call the `Credentials` class inside the sharing-credential class
?

**Comment by tahpot** [comment]
@cmcWebCode40 Yes.

The sharing class should focus just on publishing the (already created) credential to the public database and returning the URL.

**Comment by cmcWebCode40** [comment]
ok, I think I have understood  let me resolve the design issue

**Comment by nick-verida** [comment]
@cmcWebCode40 is this still an issue?

If not can you please close.

**Comment by cmcWebCode40** [comment]
No, this issue has been resolved!
