### ISSUE TITLE
Document Messaging class

### ISSUE THREAD

**Issue by nick-verida** [verida/verida-js#120]
Documentation on all classes is important. 

However it seems critical that this class in particular is documented. IN particular the `send` method is a critical piece of the Verida API that has many options. 

Please add @kalanamt and @tahpot to the review when this is done.

**Comment by tahpot** [comment]
@nick-verida

It turns out messaging is documented: https://github.com/verida/verida-js/blob/e3fb778c510a6f148013c32ee177fb3fe7476ae2/packages/client-ts/src/context/messaging.ts#L26

Do we have auto-deployment of API docs in place?

**Comment by nick-verida** [comment]
No, auto-deployment of API docs isn't in place. 

We need to keep docs synced to the code releases, and both are manual at the moment. 

I'd like to see both of these things automated, but not sure what the release process for the code is at the moment. 

There is a script in `client-ts` to generate and redeploy the docs: https://github.com/verida/verida-js/blob/main/packages/client-ts/generate-and-deploy-docs.sh

I'll run this now.

**Comment by nick-verida** [comment]
Hmm @tahpot _none_ of those annotations docs are showing up in the docs. 

Further investigation is required...

**Comment by nick-verida** [comment]
This is now fixed
