### ISSUE TITLE
Notification ping to the wrong target

### ISSUE THREAD

**Issue by pkhien95** [verida/verida-js#127]
- When the web app initiates a context to display a QR to log in, it also constructs the notification engine object: 
https://github.com/verida/verida-js/blob/34ccb33cc4a1a37e0341c0ee7628fd54c03be2f7/packages/client-ts/src/context/context.ts#L238
- But when an outbox message is sent, the ping method is using the context and did from this as parameters, I think they should be from the receiver, not from the context that is sending the message (**this**): https://github.com/verida/verida-js/blob/34ccb33cc4a1a37e0341c0ee7628fd54c03be2f7/packages/client-ts/src/context/engines/verida/notification/engine.ts#L38

**Comment by kalanamt** [comment]
@pkhien95 @tahpot   
Means instead of  returning `this.context.getContextName()` , should it return `this.context.client()` ?

**Comment by tahpot** [comment]
@kalanamt

No.

[`this.context.getContextName()`](https://github.com/verida/verida-js/blob/34ccb33cc4a1a37e0341c0ee7628fd54c03be2f7/packages/client-ts/src/context/engines/verida/notification/engine.ts#L38) is a string representing the context of the Verida account sending the message.

I think that `ping()` method needs to take a parameter of `contextName` and should be pulled from the `config` variable included in the `send()` method call:

https://github.com/verida/verida-js/blob/34ccb33cc4a1a37e0341c0ee7628fd54c03be2f7/packages/client-ts/src/context/engines/verida/messaging/engine.ts#L77

Something like `await this.notificationService.ping(config.recipientContextName)` (see [`MessageSendConfig` interface](https://github.com/verida/verida-js/blob/34ccb33cc4a1a37e0341c0ee7628fd54c03be2f7/packages/client-ts/src/context/interfaces.ts#L116))

**Comment by kalanamt** [comment]
Estimation :- 32 hrs

**Comment by Kalanamith** [comment]
ping method should return 
```
{
     "did": "target's DID",
     "contextName" :  "Name of the target"
}
```

**Comment by kalanamt** [comment]
ping method should return

{
     "did": "target's DID",
     "contextName" :  "Name of the target"
}

**Comment by pkhien95** [comment]
@nick-verida when I check CloudWatch logs, it's like this:
```
Sending ping to deviceIds:  [
  [32m'fhaBDjtkYkQQjZXrECY4qh:APA91bF87CBkciwTnBuhKVIsJvyN_L7dYRdHDt4O1LlUUfBgtFkvQ-Jmd3kGSUxaViT7Nq1wkPPp3VJYLtj6tppr0kpTH89uIHZvBXlb4CKMRFyeKBtDroVIGVvitXBV_yhbEHX6m13Q'[39m
```
The format looks strange to me as there is an array of arrays and each item has a `32m'`, `39m` prefix. @nick-verida is that just a format on CloudWatch?

**Comment by nick-verida** [comment]
> @nick-verida when I check CloudWatch logs, it's like this:
> 
> ```
> Sending ping to deviceIds:  [
>   �[32m'fhaBDjtkYkQQjZXrECY4qh:APA91bF87CBkciwTnBuhKVIsJvyN_L7dYRdHDt4O1LlUUfBgtFkvQ-Jmd3kGSUxaViT7Nq1wkPPp3VJYLtj6tppr0kpTH89uIHZvBXlb4CKMRFyeKBtDroVIGVvitXBV_yhbEHX6m13Q'�[39m
> ```
> 
> The format looks strange to me as there is an array of arrays and each item has a `32m'`, `39m` prefix. @nick-verida is that just a format on CloudWatch?

Yes, it seems to be. On the console they look like this:

Sending ping to deviceIds:  [
  'fhaBDjtkYkQQjZXrECY4qh:APA91bF87CBkciwTnBuhKVIsJvyN_L7dYRdHDt4O1LlUUfBgtFkvQ-Jmd3kGSUxaViT7Nq1wkPPp3VJYLtj6tppr0kpTH89uIHZvBXlb4CKMRFyeKBtDroVIGVvitXBV_yhbEHX6m13Q'
]

I'm not sure why it is happening.

**Comment by kalanamt** [comment]
@pkhien95  Seems incorrectly decrypted binary object , it tries to process a binary array can be a `Vec<u8>` somewhere

**Comment by nick-verida** [comment]
from @pkhien95 

> @nick-verida Sorry I missed this when started this feature: currently the server is sending a `data` type of message, which will not trigger a push notification from OS when the app is in background. We have 2 ways to resolve this:
> 
>     * Send a `notification` type of message. Official doc here: https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#notification
> 
>     * Send a "wake-up" data message:
>       
>       * iOS: add `content-available: true`
>       * Android: add `priority: high`
> 
> 
> Let me know which way do you think we should use.

I'm not sure, but it sounds like the `wake-up` message matches what we want right? We want to wake the app up and get it to poll?
