### ISSUE TITLE
account-web-vault config cache

### ISSUE THREAD

**Issue by pkhien95** [verida/verida-js#130]
After initializing the account like this:

```javascript
this.account = new VaultAccount({
			defaultDatabaseServer: {
				type: 'VeridaDatabase',
				endpointUri: VUE_APP_VERIDA_TESTNET_DEFAULT_SERVER as string,
			},
			defaultMessageServer: {
				type: 'VeridaMessage',
				endpointUri: VUE_APP_VERIDA_TESTNET_DEFAULT_SERVER as string,
			},
			defaultNotificationServer: {
				type: 'VeridaNotification',
				endpointUri: VUE_APP_VERIDA_TESTNET_DEFAULT_NOTIFICATION_SERVER
			},
			vaultConfig: {
				request: {
					logoUrl: VUE_APP_LOGO_URL,
				},
			},
		})
```
if I change the variable `VUE_APP_VERIDA_TESTNET_DEFAULT_NOTIFICATION_SERVER` it doesn't update the config inside client-ts and keep calling to the previous `endpointUri`

**Comment by tahpot** [comment]
Those config variables are only used as default values when you create a new account.

You will need to create a new account if you want to use different variables.

It is possible to manually update the service endpoints for an existing DID, however it shouldn't be necessary if the Vault is setting them correctly in the first place.

**Comment by pkhien95** [comment]
> Those config variables are only used as default values when you create a new account.
> 
> You will need to create a new account if you want to use different variables.
> 
> It is possible to manually update the service endpoints for an existing DID, however it shouldn't be necessary if the Vault is setting them correctly in the first place.

@tahpot what should we do in the case that the notification server is moved to another host (or different port)? Where does the cache for config stored and are we able to clear it if user doesn't want to create a new account?
@kalanamt I think for debugging now we can just create a new account every time we switch from local <=> testnet server.

**Comment by pkhien95** [comment]
> It is possible to manually update the service endpoints for an existing DID, however it shouldn't be necessary if the Vault is setting them correctly in the first place.

Sorry I was not clear, this code snippet is in the web app (MaPay), not the Vault. The Vault is not using `account-web-vault`

**Comment by nick-verida** [comment]
I think you'll need to create a new `Network` if you create a new `VaultAccount` too. 

Just noting that there is a PR to simplify the API for this: https://github.com/verida/verida-js/issues/95

**Comment by tahpot** [comment]
@pkhien95 @nick-verida Can this be closed?

As far as I understand it, this issue is because the account was already created, so changing the default config in the app does nothing.

**Comment by pkhien95** [comment]
Closed since the constructor of account-web-vault changed depending on initialization in the Vault, also creating new account is a solution.
