### ISSUE TITLE
[Verifiable-credential] Applications with different context name to read VCs

### ISSUE THREAD

**Issue by cmcWebCode40** [verida/verida-js#144]
## How VCs are created

- VCs are created with the issuer app `context name` and saved in an external database. 

## Problem

- The `Utils.fetchVeridaUri(createdUri, context)` throws an error if the current application does not have the same `context name` as the issuer account.

There should be a way the library handles this `context name`  issue so applications with different context names can read any VCs

**Comment by tahpot** [comment]
@cmcWebCode40 I have made a commit here in your feature branch: https://github.com/verida/verida-js/commit/fa26070ee41e67534f56a8fcdcac9a7955d30cff

This allows you to open an external database by specifying the `contextHash` for the `contextName`.

In theory if you replace `contextHash` with `contextName` [here](https://github.com/verida/verida-js/blob/55830ac7a6ba6a5cf4495d152b729d95c6097bfb/packages/client-ts/src/utils.ts#L91), it should work.

**Comment by cmcWebCode40** [comment]
<img width="1202" alt="Screenshot 2022-02-14 at 14 18 47" src="https://user-images.githubusercontent.com/54280620/153871728-ed429ecf-f602-491b-a6e7-24a48f857513.png">

@tahpot, I have used the `contextHash` from a created URI as the `contextName` and I got the above screenshot error, please can you check  the test here  [5be233c9](https://github.com/verida/verida-js/pull/143/commits/5be233c9d7e5eacc41e64b5425acbcf6db4cb4a0)

**Comment by tahpot** [comment]
@cmcWebCode40 Please review my recent commits. I have fixed some issues and all the tests now pass :)
