### ISSUE TITLE
[verifiable-credentials] add expirationDate field to VC schema

### ISSUE THREAD

**Issue by nick-verida** [verida/verida-js#145]
As discussed [in the design notes](https://docs.google.com/document/d/1ZS-xzqVpbxBOQL16zf0aRJOV2kjFJl4OFrtg1usdyGo/edit?disco=AAAAVPBZepM) it makes sense to put `expirationDate` in the schema. This makes it easier to check and provides protection against tampering (because it then gets included in the signed didJwtVC field).

This field should be optional (as some VC may not expire). 

This issue includes both the code changes to the library to make sure it is set correctly AND the updates to the schema doc itself. 

Note that the tamper-proof-clock issue in the design note is not included here. This issue supersedes the design note; ie any discussion about algorithms there that isn't included here should not be implemented.

**Comment by nick-verida** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Verida-Engineering-61ef8aa39c1cb9001f7cb0ca/issues/verida/verida-js/145?planning-poker) with ZenHub @cmcWebCode40 @tahpot

**Comment by cmcWebCode40** [comment]
@nick-verida, 

@tahpot actually fixed this issue yesterday in the call we had and wrote tests for this too.

The changes are made on this branch `feature/142-test-cases-for-vcs`
