### ISSUE TITLE
[verifiable-credentials]: Check the schema is a "credential" schema type

### ISSUE THREAD

**Issue by cmcWebCode40** [verida/verida-js#146]
Check if the schema is a [credential](https://common.schemas.verida.io/credential/base/v0.1.0/schema.json) schema type

**Comment by cmcWebCode40** [comment]
@tahpot, please I would want to understand exactly the task I'm implementing, when the `createCredentialJWT()` is called are my validating to check if the schema data must be a `credential` schema type ?

**Comment by tahpot** [comment]
@cmcWebCode40 For now check if there is a `didJwtVc` required field in the schema.

**Comment by cmcWebCode40** [comment]
@tahpot, 

```
const isValid = await schema.validate(data);
```

I think the above example (already implemented) validates the data, which means if it a credential data and it doesn't have the `didJwt` property it returns false. is that correct?

maybe this solves the issue?
