### ISSUE TITLE
[verifiable-credentials]: use the Luxon library to do the date/time comparison.

### ISSUE THREAD

**Issue by cmcWebCode40** [verida/verida-js#147]
The Luxon library linked above supports [ISO8601](https://moment.github.io/luxon/#/parsing?id=iso-8601) parsing and this is compatible with XMLSCHEMA11-2 date objects.

See comments :

https://github.com/verida/verida-js/pull/143#discussion_r806374525
https://github.com/verida/verida-js/pull/143#discussion_r806386387

**Comment by cmcWebCode40** [comment]
@tahpot , @nick-verida 

the luxon library size is 3.72 MB which can impact our VC lib size.
what are your thoughts?

**Comment by tahpot** [comment]
@cmcWebCode40 Way too big... this is a simple comparison so need something much smaller.

Do you want to look at the other library options linked to in the original ticket?

**Comment by cmcWebCode40** [comment]
@tahpot, 
sure, I will take a look at the other options.
