### ISSUE TITLE
[verifiable-credentials]: Test for VC issuanceDate

### ISSUE THREAD

**Issue by cmcWebCode40** [verida/verida-js#148]
### Create two tests 

- [ ] Test issuanceDate is within 10 seconds .
- [ ]  If no issuanceDate provided. Otherwise do a test with a user-supplied issuanceDate

**Comment by cmcWebCode40** [comment]
@tahpot,

Do I still need to check that the `issuanceDate` provided must be within 10secs creating Vc, what if a different date was provided and it's not close to the current date, how do we validate that?

cc @nick-verida

**Comment by tahpot** [comment]
@cmcWebCode40 Only test within 10 seconds, if the `issuanceDate` wasn't supplied as a parameter.
