### ISSUE TITLE
[verifiable-credentials] : Error: invalid_config: JWT audience is required

### ISSUE THREAD

**Issue by cmcWebCode40** [verida/verida-js#154]
@tahpot,
 
 from @pkhien95  he said he tried to run issueEncryptedCredential on the item object directly from the data folder and use it on the scanner-web, it throws this error:

```
Error: invalid_config: JWT audience is required but your app address has not been configured

```
However, when I add this step:

```const credentialItem = await credential.createCredentialJWT(
          AccountManager.getInstance().getSelectedAccount()?.did,
          item
        )
```
then run issueEncryptedCredential on the credential Item above, it creates a valid URI. So I think we still need to keep createCredentialJWT in the Vault?

Reproduce error 

- @pkhien95  has added a test case that can be found here  https://github.com/verida/verida-js/blob/6ba7d7ce0674c9565a2ec1d0bd15dbd8987b6655/packages/verifiable-credentials/test/share-credentials.test.ts#L83

**Comment by cmcWebCode40** [comment]
@tahpot,

from my investigation in the above error, @pkhien95 encountered trying to verify a credential issued from a fetch data by calling the credential.verifyCredential(jwt) method here is the console error that was logged from the did-jwt-vc package.


 ``` 1) Share Credential tests
       Share Credential Units
         When Verida URI is issued directly from a data object:
     Error: invalid_config: JWT audience is required but your app address has not been configured
      at /Users/chinweikemichael/Desktop/verida/verida-js/node_modules/did-jwt-vc/node_modules/did-jwt/src/JWT.ts:373:15
      at processTicksAndRejections (internal/process/task_queues.js:95:5)

```

**Comment by tahpot** [comment]
Thanks @cmcWebCode40.

I will take this one over as I think I've found an important bug.

There may be an issue with how credentials and presentations are generated. This is a blocker to a new npm release.

**Comment by cmcWebCode40** [comment]
@tahpot, 

what is the difference between the `VerifiablePresentationJwt` and the `verifiableCredentialJwt`, because I could remember initially I didn't get to utilize those methods.

**Comment by tahpot** [comment]
@cmcWebCode40 

`verifiableCredentialJwt()` creates a credential for storage
`verifiablePresentationJwt()` takes a credential and turns it into a special "presentation" object, which can contain multiple credentials.

The credential is used when you create the credential in the credential manager application. The presentation is used when sharing the credential via a QR code or Verida URL, hence that is what will be used by the Vault.

I'm going to write up proper documentation about this when I get a chance.

**Comment by tahpot** [comment]
@cmcWebCode40 @cmcWebCode40 

I've added a PR here with the bulk of the developer documentation: https://github.com/verida/documentation/pull/49
