### ISSUE TITLE
[verifiable-credentials] : tweetnacl-util package not correctly encoding to base64 in mobile vault

### ISSUE THREAD

**Issue by cmcWebCode40** [verida/verida-js#166]
The `tweetnacl-util` used in the `@verida/verifiable-credentials` lib  base64encoding works when running the tests cases but does not  base64encode the URI correctly when the package is used in the mobile vault and could not be decoded from the `web-scanner-demo` not sure why it happens that way. 

here is an example of an incorrect base64encoding it generated 

```
"https://scan.verida.io/credential?uri=AAAAAAAAAAAAAAAAAAAAAAAAAAEAAAACAAAAAAcHAAMBAAAABwcAAAUAAAMBAAQBAAIGAAAIAAEGAAMACAAAAAAFAAkAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYFCAYDAAAJAAADAAEBAAAACAIEAAAGAAgJAAAEAAUHAAAAAAAAAAMEAQAAAAAIAAQAAAAABQAEAAYAAAAJAAADAQAIAggACAcFAAcGBQAFBQAFAAAABgYJAQQDBgMHAAAGAQcAAwQ="
```
I and @pkhien95 had to replace the `encodeBase64()` method in the `tweetnacl-util` lib. that was used in the `issuePublicPresentation()`  to the code example below and it worked as expected and was decoded correctly from the `web-scanner-demo`

```
return {
	item: item,
	result: result,
	did: did,
	veridaUri: uri,
	publicUri: `https://scan.verida.io/credential?uri=${Buffer.from(uri, 'utf8').toString('base64')}`
};

```

### Example code of how the URI its been base64decoded in the `web-scanner-demo`

```
   const decodedURI = Buffer.from(uri, 'base64').toString('utf8');

```

**Comment by tahpot** [comment]
>I and @pkhien95 had to replace the encodeBase64() method in the tweetnacl-util lib

@cmcWebCode40 What was changed exactly?

I would definitely recommend against using `tweetnacl-utils` for base64 encoding / decoding. Using native Buffer to encode and decode like you have is definitely better.

Do you want to create a PR?

**Comment by cmcWebCode40** [comment]
Yes, I would create a new PR for this
