### ISSUE TITLE
[verifiable-credentials] : TypeError: @context is missing default context "https://www.w3.org/2018/credentials/v1"

### ISSUE THREAD

**Issue by cmcWebCode40** [verida/verida-js#167]
Currently getting this error  from the `@verida/verifiable-credentials` package when i call the `credentials.verifyCredential(jwt)` method .

<img width="917" alt="Screenshot 2022-03-03 at 17 38 20" src="https://user-images.githubusercontent.com/54280620/156609665-a3c51b9a-e035-498d-8998-1cdaa123ac4c.png">

**Comment by tahpot** [comment]
@cmcWebCode40 This issue needs more information.

What is the credential data that is being generated? Can you create a unit test that replicates the issue with your data?

**Comment by tahpot** [comment]
@cmcWebCode40 Is this still an issue with the updated libraries?

**Comment by cmcWebCode40** [comment]
@tahpot, no this has been resolved , it cam now be closed .

**Comment by nick-verida** [comment]
Closing
