### ISSUE TITLE
[client-ts] Ensure deterministic signature generation

### ISSUE THREAD

**Issue by tahpot** [verida/verida-js#169]
In order to support off-chain signed data on the Verida network being used on-chain, we need to ensure the signature generated for each data record is the same for each piece of data.

For example:

```
{
  "hello": "world",
  "jane": "doe"
}
```

needs to generate the same signature as:

```
{
  "jane": "doe",
  "hello": "world"
}
```

In order to do this, we need to ensure data is either:

1. Always stored in C/PouchDB in alphanumeric order
2. Always sorted into alphanumeric order before the signature is generated

Preference is for (1), however C/PouchDb may not enforce order of key / value pairs. Requires investigation.

**Comment by nick-verida** [comment]
I suspect you'll have to do (2) because the collation order for PouchDB is likely to depends on the locale settings for the browser, and different locales have different sort orders (see https://docs.microsoft.com/en-us/globalization/locale/sorting-and-string-comparison). 

I _think_ (2) and specifying the locale to be US-English (I guess?) would solve this.

**Comment by nick-verida** [comment]
Here's an example from the link above for collation order being different across launages
![image](https://user-images.githubusercontent.com/87622993/158291221-d1a6c61d-942d-49d6-8fca-0f65d981d145.png)

**Comment by tahpot** [comment]
@nick-verida Good point. This will also run on the server, so will depend on the locale of the server or browser depending on the runtime environment.

It makes sense to force US-English for determining the order. The actual doesn't really matter, just so long as it's consistent.

**Comment by tahpot** [comment]
We should consider using: https://www.npmjs.com/package/json-stable-stringify

**Comment by nick-verida** [comment]
@tahpot @pranavburnwal this seems important. Should someone work on it?

**Comment by pranavburnwal** [comment]
> We should consider using: [npmjs.com/package/json-stable-stringify](https://www.npmjs.com/package/json-stable-stringify)

https://github.com/substack/json-stable-stringify/issues/20
Based on ticket, it still doesn't sort properly. So we need to pass in a pre-sorted place. 

They suggest https://github.com/ThomasR/JSON.sortify
