### ISSUE TITLE
[verifiable-credential]: verify credential using an external context

### ISSUE THREAD

**Issue by cmcWebCode40** [verida/verida-js#170]
### Todo

Users should be able to verify a credential URI from the account explorer demo without having to login in by using an external `context` .

see @tahpot  suggestion to fix this issue :

https://discord.com/channels/664594912460668960/929954765021011978/953902907974107176

**Comment by cmcWebCode40** [comment]
@tahpot , 


I have been able to refactor the `Credential` class as suggested.

see branch 
Here are questions i want to ask 

1. Is there a way we can call the `Utils.fetchVeridaUri(data.veridaUri, context)`  and avoiding to pass the application `context`?
because this `Utils.fetchVeridaUri(data.veridaUri, context)` still requires  it.

2. Do we have where in our documentation I can open a `context.openExternalDatabase()` without connecting to a vault?

**Comment by tahpot** [comment]
@cmcWebCode40 

>I have been able to refactor the Credential class as suggested. See commit https://github.com/verida/verida-js/commit/2442b6c814a4a59e0e62f6785fd852cb3375945b

That looks good, I have added one comment regarding the unit tests.

>Is there a way we can call the Utils.fetchVeridaUri(data.veridaUri, context) and avoiding to pass the application context?

I see what you mean. In reality, `Utils.fetchVeridaUri()` should be modified to pass in a `client` not a `context`, and then open an external `context` and external database (as below).

Can you create an issue for this?

>Do we have wherein our documentation I can open a context.openExternalDatabase() without connecting to a vault?

There is some documentation [here](https://developers.verida.io/docs/client-sdk/data#external-database), however it doesn't mention how to open an external context. Here's an example of that:

Use `const context = await client.openExternalContext()` then use `const db = await context.openExternalDatabase()`.

Can you add an issue in the documentation for us to improve this?

**Comment by cmcWebCode40** [comment]
@tahpot, I have added the following tickets.

> Can you add an issue in the documentation for us to improve this?
https://github.com/verida/documentation/issues/52

> Can you create an issue for this?
https://github.com/verida/verida-js/issues/172

**Comment by cmcWebCode40** [comment]
![Screenshot 2022-03-21 at 07 10 06](https://user-images.githubusercontent.com/54280620/159215042-71193944-8b9e-4df3-8e17-959be89eeb5d.png)

@tahpot , 
all test now passed just on error .
i currently getting the above error for this test case [here](https://github.com/verida/verida-js/blob/15635dad61a427653099a58b8cb118c1acbbc6e4/packages/verifiable-credentials/test/share-credentials.test.ts#L63) , trying to open external database using the `client` class with a different `contextName`

**Comment by nick-verida** [comment]
@pranavburnwal it'd be worth you getting across this work. Michael is away for a couple more days but even if you could get it to the point you can replicate what he's seeing I think it might be helpful as preparation for taking some of this stuff off @tahpot .

**Comment by pranavburnwal** [comment]
Leaving notes here after talking to @nick-verida. PS: I plan to add things like this in Dev Documentation. 

Anatomy of shared credential URL.

Initial URL:
`https://verida.network/credential?uri=dmVyaWRhOi8vZGlkOnZkYToweGY3MzkxN2E0MzA4OEUxRDA1ODM3RmZkNTAwMTUwNzIxZWI1QzMxMzIvOENObVI1TDlZZGZBWW1mM2tYL2NyZWRlbnRpYWxfcHVibGljX2VuY3J5cHRlZC84MTQ5MWEzMC1hODA0LTExZWMtYjg5OS1jM2QxZTU0NmQ4ZWY/a2V5PTRkMzI1MjJiMThhOTBhMjliYWY5NzFhYmE5YjQ0YmE3MTFkZDhiNGRlZGNkMGEwYjhkYWM3NTM1MTYzNDJlYmE=`

Take out the Token and BASE64 decode

`verida://did:vda:0xf73917a43088E1D05837Ffd500150721eb5C3132/8CNmR5L9YdfAYmf3kX/credential_public_encrypted/81491a30-a804-11ec-b899-c3d1e546d8ef?key=4d32522b18a90a29baf971aba9b44ba711dd8b4dedcd0a0b8dac753516342eba`

```
verida://
did:vda:0xf73917a43088E1D05837Ffd500150721eb5C3132/ //Reciepient VDA
8CNmR5L9YdfAYmf3kX/ // Encrypted DB name
credential_public_encrypted/ //Table name
81491a30-a804-11ec-b899-c3d1e546d8ef //Document ID
?
key=4d32522b18a90a29baf971aba9b44ba711dd8b4dedcd0a0b8dac753516342eba
	//Key to decrypt
```
