### ISSUE TITLE
Verida-JS should provide the ability to save a login session in local storage

### ISSUE THREAD

**Issue by nick-verida** [verida/verida-js#182]
As discussed on Discord, Verida-JS needs to provide the ability to save details in local storage so different parts of an application can synchronise login. 

There is currently a partially working implementation in Verida-JS. Not sure exactly where the code is though. 

There is also an implementation here:
setSession():
https://github.com/verida/documentation/blob/dc9b5fd1227703d5a640419e1576e7c39544134d/src/theme/ReactLiveScope/index.js#L39

getSession(): https://github.com/verida/documentation/blob/dc9b5fd1227703d5a640419e1576e7c39544134d/src/theme/ReactLiveScope/index.js#L63

and can be used like this:

```
    // We use this to check if we are logged in
    if (!veridaContext) {
      // we don't have veridaContext in local state

      // see if we have a session
      ctx = await getSession(this.CONTEXT_NAME)
      if (ctx) {
        // we do, so set the state variable we expect
        setVeridaContext(ctx)
      }
```

The `disconnect` function needs to make sure local storage is cleared.

Consider how to make this work with the "Remember Login" check box. If that box is not checked then revisiting the page should not be logged in (but multiple components on the same page should): ie; this should be like a session cookie.

**Comment by nick-verida** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Verida-Engineering-61ef8aa39c1cb9001f7cb0ca/issues/verida/verida-js/182?planning-poker) with ZenHub @cmcWebCode40 @pranavburnwal

**Comment by cmcWebCode40** [comment]
Hi @nick-verida, 

from this` loadFromSession()` here in the library https://github.com/verida/verida-js/blob/164ab26622fda6e7f47cafa3f177b653c8723de5/packages/account-web-vault/src/vault-account.ts#L78}

I think it does solves our problem, we could expose this method so that developer can retrieve the user `context` if there's a login session.

cc @tahpot @pranavburnwal

**Comment by nick-verida** [comment]
> Hi @nick-verida,
> 
> from this` loadFromSession()` here in the library [https://github.com/verida/verida-js/blob/164ab26622fda6e7f47cafa3f177b653c8723de5/packages/account-web-vault/src/vault-account.ts#L78}](https://github.com/verida/verida-js/blob/164ab26622fda6e7f47cafa3f177b653c8723de5/packages/account-web-vault/src/vault-account.ts#L78%7D)
> 
> I think it does solves our problem, we could expose this method so that developer can retrieve the user `context` if there's a login session.
> 
> cc @tahpot @pranavburnwal

When I tested that it didn't work. This is what I was referring to when I said:

> There is currently a partially working implementation in Verida-JS. Not sure exactly where the code is though.

However we were having other login issues at the time, so it is possible they were affecting it. Probably worth retesting.

If it doesn't work then this method should be replaced by one that does.

**Comment by cmcWebCode40** [comment]
@nick-verida, @pranavburnwal, @tahpot 

Just to be clear , 

- The `connectContext()` in the `VaultAccount` class  stores the app context config in the localStorage using a key named `_verida_auth_context` .

- If the `connectContext()` is been triggered again it retrieves the app `contextConfig` stored in the localStroge(if it exists) which will be used to fetch the app `context`.

seems like what we are trying to achieve here is been done already just that the difference here is that the localStorage key name is different

My suggestions of what we can do here: 
 1. We can change the `_verida_auth_context` to `(the app contextName) instead  ?.
 2. Store add the `context` in the existing contextConfig object?
 
 - here is an example of the config stored in the local storage
 ```
{
    "signature": "0xd109b2752d75a2bc5e26ce5e1f3f997e1161eae20873dedfd5dc6bf0b2b2b75d4eeb04093d533d89786cfbfa04f303536974c95e053706bf0257be0a1d4ae6651c",
    "did": "did:vda:0xF63de3c69d8ECbF1c320D80FED3306C364Bd29b6",
    "contextConfig": {
        "id": "Verida:Account Explorer",
        "publicKeys": {
            "asymKey": {
                "type": "Curve25519EncryptionPublicKey",
                "publicKeyHex": "0xd74d5bb4e37d4c69de629e0830395bf60b0ec6ebd1b7e0625ffdb3320f76f006"
            },
            "signKey": {
                "type": "EcdsaSecp256k1VerificationKey2019",
                "publicKeyHex": "0x0242ea8b6ef42ca3b9612844a461b1cecba9170a372f228bf9996c06809d0d74c2"
            }
        },
        "services": {
            "databaseServer": {
                "type": "VeridaDatabase",
                "endpointUri": "https://db.testnet.verida.io:5002/"
            },
            "messageServer": {
                "type": "VeridaMessage",
                "endpointUri": "https://db.testnet.verida.io:5002/"
            },
            "notificationServer": {
                "type": "VeridaNotification",
                "endpointUri": "https://vpns.testnet.verida.io:5011"
            }
        }
    },
    "context": "Verida:Account Explorer"
}
 
 ```
 
 What are your thoughts?

**Comment by tahpot** [comment]
Hey all.

I don't think there is an issue here.

[hasSession()](https://github.com/verida/verida-js/blob/164ab26622fda6e7f47cafa3f177b653c8723de5/packages/account-web-vault/src/vault-account.ts#L16) exists to check if a session already exists for a given context. I have just tested this and it definitely works. I see this isn't in our documentation, but should be.

If a session already exists and you use the verida libraries to open a context that exists in the session, it will automatically open the context without displaying the QR code. This happens via the `loadSession`, but that is internal code and isn't intended to be called externally.

You can test this in the [web-sandbox](https://web-sandbox.demos.testnet.verida.io/). Copy / paste the code to login via QR code. Reload the page. Re-run the same code and you will be automatically logged in with your DID displayed in the console.

As such, the recommended way to achieve this is to:

1. Call `hasSession()` to determine if the user is already logged in.
2. If user has a session, open the context as you would normally and it will auto-login.
3. If the user doesn't have a session, the application assumes the user is logged out and doesn't open a context until they need to login

**Comment by tahpot** [comment]
In regards to [disconnect()], this definitely works as expected.

Again, in the websandbox call `context.disconnect()` after logging in. Reload the page and open the context, you will be asked to login.

**Comment by tahpot** [comment]
I have also exposed `hasSession()` in web sandbox to help with testing.

See https://github.com/verida/web-sandbox/commit/eb4058507e121e39fbaf15ca9331b311364404f9

**Comment by cmcWebCode40** [comment]
@nick-verida 

concerning @tahpot response to this issue ticket , 

here are the lines of code where i have implemented  this in our vue-account-component using the `hasSession()` 

https://github.com/verida/verida-vue-components/blob/183693e1eab181b0c59f153a93b658e4b5660ed0/components/account/src/helpers/VeridaHelper.ts#L85

https://github.com/verida/verida-vue-components/blob/183693e1eab181b0c59f153a93b658e4b5660ed0/components/account/src/lib-components/vda-account.vue#L123

**Comment by nick-verida** [comment]
I've tested `hasSession` and can confirm it works. 

It seems likely that my problems with it before were actually the Vault issue around login at the time. 

Closing this issue in favour of:
* https://github.com/verida/verida-vue-components/issues/57
* https://github.com/verida/documentation/issues/69
