### ISSUE TITLE
Enforcing tombstones instead of deleting documents

### ISSUE THREAD

**Issue by benlongstaff** [verida/verida-js#19]
From the confidential storage working group [discussion](https://github.com/decentralized-identity/edv-spec/issues/21) and  [spec](https://identity.foundation/confidential-storage/#encrypteddocument)

"Delete Resource (Document or Stream): Deletes the encrypted resource (note that a tombstone object should remain behind for replication purposes)."

- [ ] Verify how tombstones is currently enforced.
- [ ] Check that the database access permissions don't allow users / applications to delete documents

**Comment by tahpot** [comment]
CouchDb uses `_deleted` property, this ensures replication of deletions occurs across nodes. No action required.

Database owners can complete whole databases, but not hard delete individual docs.
