### ISSUE TITLE
[web3] Create a verida web3 client

### ISSUE THREAD

**Issue by tahpot** [verida/verida-js#191]
Create a client library that extends the web3 library and supports making gasless transactions via the Verida gasless server OR just natively via the blockchain.

Create a `VeridaWeb3Proxy` library:

- As a developer I can configure the `VeridaWeb3Proxy` to use a web3 instance I provide so that I can interact with Verida smart contracts
- As a developer I can configure the `VeridaWeb3Proxy` to use the Verida Gasless Server so that I can interact with Verida smart contracts
- As a developer I can use the proxy to execute a transaction on a smart contract

Example configuration if using Web3 instance and therefore paying gas fees:

```
const web3 = new Web3('https://....')
const web3Proxy = new VeridaWeb3Proxy({
  config: {
    contractAddress,
    abi,
    web3: web3
  }
  type: 'web3',
})
```

Example configuration if using Verida gasless and therefore paying no gas fees:

```
const client = new VeridaClient(...) // configure a connection to the Verida network, like we currently do
const web3Proxy = new VeridaWeb3Proxy({
  type: 'gasless',
  config: {
    veridaClient: client,
    contractName: 'DIDRegistry',
    headers: {
      'User-Agent': 'Verida-Client'
    }
  }
})
```

Executing a transaction:

```
web3Proxy.sendTransaction(..)
```

**Comment by tahpot** [comment]
@ITStar10 is currently researching how other projects, such as Biconomy do this.

**Comment by tahpot** [comment]
Next steps:

- @ITStar10 create a basic working version
- @tahpot and @ITStar10 have another call to review and discuss architecture
- Implement client libraries for `did-registry` and `name-registry` that uses the Web3Proxy

**Comment by tahpot** [comment]
@pranavburnwal Can this be closed now?

**Comment by pranavburnwal** [comment]
Yes we can close this but lets wait once we merge back into `verida-js`
