### ISSUE TITLE
Remove ceramic from packages

### ISSUE THREAD

**Issue by nick-verida** [verida/verida-js#196]
We still have ceramic declared as a dependency and [imported in some code](https://github.com/verida/verida-js/blob/0b3ebf1409974595a345371e17a91f24c5ca3e7e/packages/account-web-vault/src/vault-account.ts#L1).

**Comment by nick-verida** [comment]
@cmcWebCode40 can you please clear up these dependencies. @pranavburnwal should review changes.

**Comment by pranavburnwal** [comment]
@cmcWebCode40  You can finish this with a few lines to remove. 

https://github.com/verida/verida-js/blob/0b3ebf1409974595a345371e17a91f24c5ca3e7e/packages/account-web-vault/src/vault-account.ts#L159

It is just for throw error, we can safely remove the same.

My assumption is this never got implemented.

**Comment by cmcWebCode40** [comment]
@pranavburnwal, it has been removed already because I cant see where ceramic is mentioned in the code.

**Comment by pranavburnwal** [comment]
> @pranavburnwal, it has been removed already because I cant see where ceramic is mentioned in the code.

As this is no longer visible in `main` branch
https://github.com/verida/verida-js/blob/c03b336e9488f4b90322c891aa9b0b41c6ffdcc4/packages/account-web-vault/src/vault-account.ts#L1
Closing ticket.
