### ISSUE TITLE
[did-client] Migrate to decentralized DID registry

### ISSUE THREAD

**Issue by tahpot** [verida/verida-js#210]
Use https://github.com/verida/blockchain-vda-web3-client to connect to the verida did registry on-chain.

See a video here describing the changes: https://www.loom.com/share/a695651dc27a4a7abf5e0a9c996d3677?from_recorder=1&focus_title=1

**Comment by pranavburnwal** [comment]
Please use the gasless as defaults if the config is not provided.

**Comment by ITStar10** [comment]
I need to clarify some stuffs to implement curret `did-client` library.
## 1. did-document get
There is no such function in the vda-did-registry contract.
We need to get all events for given DID, parse these events, and create document from these events.
I think Verida DID document was a bit different from the original did document. I can't find the comments for that.
And to create DIDDocument inside did-client.ts, I need the detailed structure of VDA did-document.

Before, create DIDDocument was duty on did-resolver. 
**_If we createad DIDDocument here, what's the purpose of did-resolver?_**

## 2. did-document save
There is no such function in the contract.
Our SDK users will modify DIDDocument in their codes.
To save these changes, I need to get original DIDDocument and compare with updated ones. Then call functions for only changes to save the fees.
_**Is that right?**_

## 3. signature creation
There is a problem to create signature of contract transactions. Need to know DID, nonce, parameters, & private key of DID.
If SDK users use their private key directly, it can be hacked by attackers.
And as said above, need to know all the parameters to create signature.
**_Do we need to create a library for signauture or implement this inside this verida-js library?_**

**Comment by tahpot** [comment]
**Purpose of existing libraries:**

- [did-client](https://github.com/verida/verida-js/tree/main/packages/did-client): A single client library that supports `get()` and `set()` a DIDDocument. This was necessary because we had a centralized API server and we required a client library to communicate with the server.
- [did-document](https://github.com/verida/verida-js/tree/main/packages/did-document): A helper library designed to locally generate DIDDocuments (typescript enabled). Provides methods to help easily generate DIDDocuments with the correct data required by the Verida network (ie: application contexts with public keys that point to storage nodes). `DIDDocument` typescript interface comes from [DID resolver library](https://www.npmjs.com/package/did-resolver) (`import { DIDDocument as DD } from 'did-resolver'`)
- [did-resolver](https://github.com/verida/verida-js/tree/main/packages/did-resolver): A very basic implementation of a DID resolver (again see [did-resolver](https://www.npmjs.com/package/did-resolver) that matches the expected did-resolver interface for resolving DIDs. This needs to be entirely replaced with a forked version of `ethr-did-resolver` because the current version uses `did-client` and our server API to locate DID documents.

**Proposed changes:**

- `vda-did-resolver`: Replace this with a forked version of `ethr-did-resolver` so that we can `get` any DID.
- `did-client`: Update the `get()` method to simply use `vda-did-resolver` to return a DIDDocument. Update the `set()` method to save the DIDDocument to the blockchain. See [ethr-did](https://github.com/uport-project/ethr-did) library or use existing code from [vda-did-registry](https://github.com/verida/blockchain-contracts/tree/develop/VDA-DID-Registry).
- `did-document`: No changes as it's just a helper method to support making changes to a local DIDDocument.

**Use case:**

1. Load a DIDDocument via `did-client` (which internally uses `vda-did-resolver`)
2. Make some local changes to the loaded DIDDocument
3. Call `did-client.set(DIDDocument)`
4. Problem: How to know what has changed as the blockchain should only call methods for the changes

**Update process:**

1. Call `did-client.set(DIDDocument)`
2. Fetch the blockchain version of the document (did-client.get())
3. Call a new method `DIDDocument.compare(DIDDocument)`
4. Iterate through the changes and write them on chain

**Comment by ITStar10** [comment]
## Creating DID document
We need 3 libraries relating DID document : `vda-did`, `vda-did-resolver` & `vda-web3-client`.
Here, `vda-did` is forked from `ethr-did` and `vda-did-resolver` from `ethr-did-resolver`.
As our `vda-web3-client` supporting 2 modes for smart contract interactions, we should update `vda-did-resolver` & `vda-did` libraries.

## Vda-DID-Resolver
`vda-did-resolver` create a DID document by parsing events from `vda-did-registry` contract.
There are 2 main classes of VdaDidResolver & VdaDidController.
VdaDidResolver creates a DID document and VdaDidController interacts with did-registry contract.

#### VdaDidResolver
As VdaDidResolver class only reads events from chains, I used original code with some updates.
#### VdaDidController
Updated this to use our vda-web3-client for smart contract interactions.

## Vda-DID
This library provides all smart contract functions thus developer can use this. And all the test codes regarding DID documents are existing in this library.

Updated this library for updated vda-web3-client. Updated configuration of creating instance, and test codes.

## Vda-Web3-Client
Before, we created Vda-Web3-Client with only web3-provider. 
Now updating to support various input params to create an instance. This will be more convenient for our SDK users.
Also, previous SDK version input parameters are not compatible with Vda-DID-Resolver & Vda-DID.

## Test Status
Tested updated vda-did & vda-did-resolver. And got successed in creating a did-document. But this was tested with previous version of Vda-Web3-Client.
Need tests with updated vda-web3-client

## Process for verida-js
Once above 3 libraries are completed, only one step of "set DID document" will be remaining.
For set() function of verida-js, need to find changes by comparing with previous DID document, and call necessary functions to update. So not complicated once vda-did-XX libraries ready.

**Comment by tahpot** [comment]
See additional discussion via #213

**Comment by ITStar10** [comment]
## # extensions for attributes in DIDDocument
### Structure of DIDDocument
A DIDDocument is structured as follows:
```
{
  "@context": [
    "https://www.w3.org/ns/did/v1",
    "https://w3id.org/security/suites/secp256k1recovery-2020/v2"
  ],
  "id": "did:vda:0x61:0x02ac49094591d32a4e2f93f3368da2d7d827e987ce6cdb3bd3b8a3390fde8fc33b",
  "verificationMethod": [
    {
      "id": "did:vda:0x61:0x02ac49094591d32a4e2f93f3368da2d7d827e987ce6cdb3bd3b8a3390fde8fc33b#controller",
      "type": "EcdsaSecp256k1RecoveryMethod2020",
      "controller": "did:vda:0x61:0x02ac49094591d32a4e2f93f3368da2d7d827e987ce6cdb3bd3b8a3390fde8fc33b",
      "blockchainAccountId": "eip155:4:0x80155C25E363Ee9e1BbBCC08cD5Df7CD249A98C4"
    }
 ],
  "authentication": [
    "did:vda:0x61:0x02ac49094591d32a4e2f93f3368da2d7d827e987ce6cdb3bd3b8a3390fde8fc33b#controller",
  ],
  "assertionMethod": [
    "did:vda:0x61:0x02ac49094591d32a4e2f93f3368da2d7d827e987ce6cdb3bd3b8a3390fde8fc33b#controller",
  ],
  "service": [  ]
  "keyAgreement": [  ]
}
```
### Delegate
#### **_Add to blockchain_**
To add a delegate, we can call addDelegate() function of vda-did(JS library) or DIDRegistryContract(Blockchain smart contract).
Function parameter is as following:
```
function addDelegate(
  delegate : address // hexdecimal value in 40 length
  delegateType : 'veriKey'|'sigAuth'|'enc'
  validity : number // integer value
)
```
Once added, a new event is created in the blockchain:
```
event DIDDelegateChanged(did, delegateType, delegate, ...)
```
#### **_Resolve DIDDocument_**
`vda-did-resolver` library parse above events and generate `did-document`.
Parsing above events creates different objects in the document. It depends on the `delegateType` of the event.

If `delegateType` is **sigAuth**, it creates an object in the `authentication` of the document:
```
{
  ...
  "authentication": [ `${did}#delegate-${delegateCount}` ],
  ...
}
```
If `delegateType` is **veriKey**, it creates an object in the `verificationMethod` of the document:
```
{
  ...
  "verificationMethod": [ 
    { id: "xx", type: "xx", controller: "xx", blockchainAccountId: "xx" }
  ],
  ...
}
```
### Attribute
#### **_Add to blockchain_**
We use `setAttribute()` function of vda-did(JS library) or DIDRegistryContract(Blockchain smart contract).
Function parameter is as following:
```
function setAttribute(
  key : bytes32
  value : bytes
  validity : number // integer value
)
```
Here, key is a string value of following structure:
```
did/<"pub"|"svc">/<key algorithm>/<key purpose>/<encoding>
```
Here "pub" is for attributes and "svc" for services.
**key algorithm** : Secp256kl | Ed25519 | Rsa | X25519
**key purpose** : "veriKey | sigAuth | enc
**encoding** : hex | base64 | base58 | pem | value

Once added, a new event is created in the blockchain:
```
event DIDAttributeChanged(did, key, value, ...)
```

#### **_Resolve DIDDocument_**
`vda-did-resolver` library parse above events and generate `did-document`.
Parsing above events creates different objects in the document. It depends on the `delegateType` of the event.

If the events is for attributes (in case `key` starting with `did/pub/....`), the resolver creates objects in **verificationMethod**, **authentication**, & **keyAgreement**. And this depends on the each part of `key` value.
- Created object in **verificationMethod** is structured in following format:
```
{
  id: 'xx', 
  type:`${<key algorithm>}${<type>}`,
  controller: did
  publicKeyHex | publicBase64 | publicBase58 | publicPem | value : 'xx'
}
```
Here the 4th field is created by **<encoding>** value in the `key` string.
For example if the key string is "did/pub/Secp256kl/sigAuth/hex, the 4th field is `publicKeyHex : 'xxx'`.

- If **<key purpose>** value is 'sigAuth', the resolver created an object in **authentication** of document.
- If **<key purpose>** value is 'enc', the resolver created an object in **keyAgreement** of document.

### **did-document** package of Verida-JS library 
Current **did-document** package of Verida-JS library has only 2 function to update : `addContextSignKey()` & `addContextAsymKey()`.
#### addContextSignKey()
This function creates object in **verificationMethod** and **assertionMethod**.
Created object in **verificationMethod** is as following:
```
{
  id: `${this.doc.id}?context=${contextHash}#sign`,
  type: "EcdsaSecp256k1VerificationKey2019",
  controller: this.doc.id,
  publicKeyHex: publicKeyHex
}
```
We should generate 'key' and 'value' fields that will be passed to `setAttribute()` function.
When the resolver parse the 'DIDAttributeChanged' event, the `type` field value of **verificationMethod** object is generated by `${<key algorithm>}${<type>}`. 
Here, we can deduce that:
<key algorithm> : Secp256kl
And this object contains 'publicKeyHex' field,
<encoding> : hex
Finally, as this function doesn't create an object in **keyAgreement** of document, we can decide <key purpose>:
<key purpose> : veriKey

Now we can call `setAttribute()` function with following parameters:
```
  key: did/pub/Secp256kl/veriKey/hex
  value: xx
```
#### addContextAsymKey()
We can call `setAttribute()` function with following parameters:
```
  key: did/pub/<undefined key algorithm>/enc/hex
  value: ...
```

## Updates vda-resolver
To add # extension in 'id' field of objects in **verificationMethod**, we should update vda-resolver.
While parsing events, we can add # extensions in the id field.

To do this, we need to add values for # extension on call of `setAttribute()` function.
As you can see the parameters of `setAttribute()` function, the 'key' parameter is restricted by 32 in length. So we should add # extension values in 'value' parameter'.

We can call `setAttribute()` function as following:
```
setAttribute(
  key: did/pub/Secp256kl/veriKey/hex,
  value: `${<original value>}##${<context-hash>}`
  ...
)
```

**Comment by tahpot** [comment]
1. Update [did-document](https://github.com/verida/verida-js/blob/c03b336e9488f4b90322c891aa9b0b41c6ffdcc4/packages/did-document/src/did-document.ts#L168) to specify the correct verification key type: `X25519KeyAgreementKey2019`.

2. Use `?context=` format for specifying the context

```
setAttribute(
  key: did/pub/Secp256kl/veriKey/hex,
  value: `${<original value>}?context=${<context-hash>}`
  ...
)
```

3. Update `service endpoint` implementation to be the same

**Comment by tahpot** [comment]
**Latest update:**

1. [Pending PR 1 in did-resolver](https://github.com/verida/blockchain-vda-did-resolver/pull/1)
2. [Pending PR 2 in did](https://github.com/verida/blockchain-vda-did/pull/2)
3. [Pending PR 2 in web3 client](https://github.com/verida/blockchain-vda-web3-client/pull/3)
4. [Pending PR 215 in verida-js to bring the above three repos into verida protocol](https://github.com/verida/verida-js/pull/215)
5. [Pending PR 211 in verida-js to use the new decentralized did registry](https://github.com/verida/verida-js/pull/211) -- not tested yet

**Still required:**

1. Alex: [PR1](https://github.com/verida/blockchain-vda-did-resolver/pull/1), [PR2](https://github.com/verida/blockchain-vda-did/pull/2), [PR3](https://github.com/verida/blockchain-vda-web3-client/pull/3) need to be reviewed and merged
2. Pranav: Review PR1, PR2, PR3
3. Alex: Update [verida-js PR 215](https://github.com/verida/verida-js/pull/215) to use the latest code from 1,2,3 above
4. Alex: Merge [PR 211](https://github.com/verida/verida-js/pull/211) into [PR 215](https://github.com/verida/verida-js/pull/215) so all the changes are in a single branch
5. Alex: Need to write unit tests in [verida-js/did-client](https://github.com/verida/verida-js/tree/main/packages/did-client)
6. Alex: [Update test code](https://github.com/verida/blockchain-vda-did/blob/faba6329bd2d207075c10fe61ededf5b3ea4539c/src/__tests__/bsc.test.ts#L265).
  - Ensure `?context=...` is not encoded.
  - Ensure `hex` encoding is being used for hex public keys
7. Alex: Update [did-document](https://github.com/verida/verida-js/blob/c03b336e9488f4b90322c891aa9b0b41c6ffdcc4/packages/did-document/src/did-document.ts#L168) to specify the correct verification key type: X25519KeyAgreementKey2019
8. Chris: Review the merged code after Pranav

**Target:**

1. Alex complete tests by end of Wednesday
2. Pranav review when he can
3. Chris to review once complete

**Comment by tahpot** [comment]
**Latest update:**

- Alex: Working on write unit tests in [verida-js/did-client](https://github.com/verida/verida-js/tree/main/packages/did-client) (work in progress, aim for completion by Monday)
  - (done) Ensure ?context=... is not encoded.
  - (done) Ensure hex encoding is being used for hex public keys

**Still required:**

- Pranav: Review PR1, PR2, PR3, then Alex to merge
- Alex: Update [did-document](https://github.com/verida/verida-js/blob/c03b336e9488f4b90322c891aa9b0b41c6ffdcc4/packages/did-document/src/did-document.ts#L168) to specify the correct verification key type: X25519KeyAgreementKey2019
- Chris: Review the merged code after Pranav

**Comment by pranavburnwal** [comment]
Steps:
1. DID-Documents update as we have been using code of DID-documents from the DID-Resolver
2. Resolve test cases in case of disparities
3. -------
4. Merge PR For DID-Registry Contract upgradable 
5. Merge PR for Nonce and Proof DID-Registry Contract  
6. ---------
7. Merge VDA-Gasless-Server
8. Merge VDA-Web3-Client
9. Merge VDA-DID-Resolver
10. Merge VDA-DID
11. Merge DID-Client Package into verida-js
12. ---------
13. Test all packages and all test cases in `verida-js`
14. ----------
15. Merge all libs to Monorepo
16. Update all readme files with all information. (this step is done last to take precedence with code first)
