### ISSUE TITLE
Verida-js infrastructure for blockchain interaction

### ISSUE THREAD

**Issue by ITStar10** [verida/verida-js#213]
## First, hierachy of verida-js.
We're using vda-did-resolver in verida-js. vda-did-resolver mainly consists of 2 classes - VdaDidResolver & VdaDidController.

Here, VdaDidResolver parse did-registry-contract events in blockchain(Polygoin in our case) and create did-document. This class only read status of blockchain. So we don't need to use our verida-web3-client in this class.
I suppose to keep original VdaDidResolver codes with some updates to create did document.

VdaDidController class interacts with didRegistryContract. We've already created our verida-web3-client to make transactions into blockchain. So not sure whether or not to use this class.
Here is one stuff to consider. Our verida-web3-client is used for all verida contracts, not only for did-registry-contract. Therfore, we can't customize input parameters in case of direct 'web3' mode (We are customizing input parameters in 'gasless' mode by config function).
This makes using our verida-web3-client a bit unconvenient because of different input params for 'gasless' & 'web3' mode.
Using VdaDidController, we can customize input params and call our verida-web3-client function. This will make developers easy to interact with our Vda-DID-Regisry contract.

### Current status
Almost updated vda-did-resolver & vda-did libraries. Now testing features.
### Question
**_Do we use VdaDidController class or directly verida-web3-client in verida-js?_**

## Second, Input params of vda-web3-client in case of 'web3' mode.
Now, vda-web3-client get received 2 params of provider & account for blockchin interaction.
prvoider - This should be an web3 provide that is already connected transaction signers.
account - Signer of transaction : metamask account

### Cons of current structure: 
- Developers can't change transaction signers once created vda-web3-client instance.
- Developers can't create our verida-web3-client in direct mode with their private key only. They need to create provider with private key on their side and use this created provide for our verida-web3-client instance.
- Call override in transaction: At the moment, I didn't add additional params to override transaction params. Developers might want to change some transaction params such as gaslimit.

I thouoght, current disadvantages can be implemented & updated as project going forward.

### Question
**_Do we need to update current cons right now or later when necessary?_** 

## Help needed to link libraries
I exported a function in vda-web3-client. And inside vda-did-resolver project, I linked by yarn link @verida/web3. There was an issue of 'Function not exported ...' while compiling. I added @verida/web3 path manually in package.json of vda-did-resolver project:
![image](https://user-images.githubusercontent.com/15656252/177463213-7b4f130f-9f10-44cf-a14e-bf1bd8a71fa8.png)
After that, I could compile vda-did-resolver. Same issue while compiling vda-did that depends on vda-did-resolver library.
Not sure whether this'd be resolved once we published libraries into NPM.

**Comment by tahpot** [comment]
**DID related libraries:**

- Generate a DID document object from the blockchain (`vda-did-resolver`)
 - Reading all the events on the blockchain
 - Generates a local DID document object
- Create a new DID document on the blockchain (`vda-did` (depends on `vda-did-resolver`) using `VdaDidController` class from `vda-did-resolver`)
- Update an existing DID document on the blockchain (`vda-did` (depends on `vda-did-resolver`) using `VdaDidController` class from `vda-did-resolver`)

@ITStar10 is updating the constructor of `vda-did-resolver` and `vda-did` to support `@verida/web-client` as the connection to the blockchain. This work is complete, but needs more tests.

Require tests to be updated to use `@verida/web-client` library. No need to support raw blockchain tests through these libraries as that is supported by `@verida/web-client` via configuration (`web3` mode as opposed to `gasless`).

**Comment by tahpot** [comment]
Update today.

>Move `vda-did-resolver` from a separate library into the `verida-js` monorepo (vda-did-resolver) and leave the existing did-resolver (we will remove that later).

Not yet.

>Move `vda-did` from a separate library into the `verida-js` monorepo (vda-did).

Not yet.

>Update [did-client](https://github.com/verida/verida-js/tree/main/packages/did-client) to support get() and set() DID Document objects.

In progress.

>`did-client` constructor will be updated to accept a `@verida/web-client` instance.

In progress.

>`did-client` will use `vda-did-resolver` and `vda-did` to read and write DID Document objects.

In progress.

## Next steps:

- Focus on `did-client` and `verida-js` changes
- @ITStar10 to update in discord when there are initial interfaces / code review
- Put a hold on the performance tests. We will run these using the updated libraries once completed.

**Comment by pranavburnwal** [comment]
Ref: https://github.com/verida/verida-js/pull/215/files

**Comment by pranavburnwal** [comment]
> > Move `vda-did-resolver` from a separate library into the `verida-js` monorepo (vda-did-resolver) and leave the existing did-resolver (we will remove that later).

Done.
> 
> > Move `vda-did` from a separate library into the `verida-js` monorepo (vda-did).
> 
Done
