### ISSUE TITLE
Move vda-did-resolver from a separate library into the verida-js monorepo

### ISSUE THREAD

**Issue by pranavburnwal** [verida/verida-js#216]
Move vda-did-resolver from a separate library into the verida-js monorepo (vda-did-resolver) and leave the existing did-resolver (we will remove that later).

**Comment by pranavburnwal** [comment]
Reference #210 #213

**Comment by tahpot** [comment]
Completed by @ITStar10, in code review.

See PR https://github.com/verida/verida-js/pull/215
