### ISSUE TITLE
Update did-client to support get() and set() DID Document objects.

### ISSUE THREAD

**Issue by pranavburnwal** [verida/verida-js#218]
Update [did-client](https://github.com/verida/verida-js/tree/main/packages/did-client?rgh-link-date=2022-07-07T06%3A20%3A26Z) to support get() and set() DID Document objects.

**Comment by pranavburnwal** [comment]
Reference #210 #213

**Comment by tahpot** [comment]
@ITStar10 working on this still

**Comment by pranavburnwal** [comment]
@ITStar10 

Commented on your review.
@tahpot | Verida Just one question.
Just working on set() function of did-client.
I can see only 3 functions in current did-document package of verida-js library:
addContextService
addcontextSignKey
addContextAsymKey
Only these functions are used to update did-document in verida-js?
In the original DIDDocument, we can add/remove delegatekey, attributes & serviceendpoints. Also we can change the owner.
But not able to such functions in current DID-Document package.
Do we need to add these features to DID-Document package later?
And the delegate key formats are different from original DID Document.
Which one should I use?

**Comment by pranavburnwal** [comment]
@tahpot  Said:


The current code structure does the following:

1. Create / update a DID document instance object in Javascript. This is then exported to JSON.
2. Take the exported DID document JSON and save it to the centralized database

This works well because it's possible to save the whole DID document in a single API call.

The new code structure does the following:

1. Create a DID document on chain
2. Update the DID document with individual events for adding service endpoints, attributes etc.
3. Getting a DID document requires rebuilding the DID document via all the events

This approach requires an update to specifically update the blockchain with what has changed, instead of a snapshot of the whole DID document.

As mentioned in the [Github issue](https://github.com/verida/verida-js/issues/210#issuecomment-1164501406):

Update process:

- Call did-client.set(DIDDocument)
- Fetch the blockchain version of the document (did-client.get())
- Call a new method DIDDocument.compare(DIDDocument)
- Iterate through the changes and write them on chain

We have proposed creating the concept of a compare() method where you can identify what has changed, and then call the appropriate method (attributes, serviceendpoints) to update the DID doc. This is where you will need to internally call the attribute, serviceendpoints that already exist to update the blockchain DID document. This will be happening inside the updated did-client library, not in our DID Document library.

>Do we need to add these features to DID-Document package later?

No. But you will likely need to implement them in did-client for this update to work, as explained above.

>And the delegate key formats are different from original DID Document.
>Which one should I use?

Can you explain this in more detail? It may need it's own github issue?

**Comment by pranavburnwal** [comment]
@ITStar10 

Just before, uploaded current codes for did-client.
Please have a look:
https://github.com/verida/verida-js/blob/92a355c585da4c6359a8b6436e0b4c340a5874d6/packages/did-client/src/did-client.ts#L237
Line 224 ~ LIne 235: Remove common elements between original doc & updated doc.
Line 239 ~ Line 266: Update elements that was in the original doc
Line 269 ~ Line 296: Add newly created element
In the current addContextSignKey() of did-document package, it adds following item in verificationMethod:
Image
In the original DIDDocument, there is no item with id of above style.
Currently DID-Resolver parse only following ids for verification method:
- "id": "did:ethr:0xb9c5714089478a327f09197987f16f9e5d936e8a#controller"  // This is for controller
- "id": "did:ethr:0x0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798#controllerKey" // This is for controller key
- "id": "did:ethr:0xf3beac30c498d9e26865f34fcaa57dbb935b0d74#delegate-1" // All other items in Verification Method
And in the addContextAsymKey() function:
![image](https://user-images.githubusercontent.com/15976005/179451327-1fd22024-f61c-4f36-8a70-02928a9778b1.png)

Above id for addContextAsymKey() function is also not supported in original DIDDocument.
And keyAgreement is different from original one.
Original keyAgreement keeps only ids without suffix of '?context=...'.
As you know, DIDDocument is generated by parsing events on the chain. Items in document.VerificationMethods can be generated by 2 events of DIDDelegateChanged & DIDAttributeChanged.
In the above screenshots, items should be updated by AttributeChanged events because they contains 'publicKeyHex' field in it. Looks like, we need to add 'sign' & 'asym' as key purpose to support above types.
 If we don't update anymore current did-document package, we need to update did-resolver again.

**Comment by tahpot** [comment]
`vda-did-resolver` doesn't support query parameters in the verification method and service endpoint ID's.

@ITStar10 previously added support for this in the smart contract (see https://github.com/verida/blockchain-contracts/issues/10#issuecomment-1054180392).

Now we need to update the client side library to support this as well.

**Comment by tahpot** [comment]
We currently generate the ID for a verification method using this code: `${this.doc.id}?context=${contextHash}#sign`

The current `did-resolver` client library requires conversion into the correct format for emitting an even on-chain that relates to this verification method. The format on-chain is:

`did/pub/(Secp256k1|RSA|Ed25519|X25519)/(veriKey|sigAuth|enc)/(hex|base64|base58)`

---

Example of an existing Verida DID Document snippet showing the Verification method `id`:

```
 {
        "id": "did:vda:0x01298a7ec3e153dac8d0498ea9b40d3a40b51900?context=0x84e5fb4eb5c3f53d8506e7085dfbb0ef333c5f7d0769bcaf4ca2dc0ca4698fd4#sign",
        "type": "EcdsaSecp256k1VerificationKey2019",
        "controller": "did:vda:0x01298a7ec3e153dac8d0498ea9b40d3a40b51900",
        "publicKeyHex": "0x02a0d11560fcdafbcd7f57a4e74e6df823216e72eeb8d938f5b3a6cd31d9f4787a"
},
```

So we have the id `did:vda:0x01298a7ec3e153dac8d0498ea9b40d3a40b51900?context=0x84e5fb4eb5c3f53d8506e7085dfbb0ef333c5f7d0769bcaf4ca2dc0ca4698fd4#sign`

Which maps to:

`did:vda:0x01298a7ec3e153dac8d0498ea9b40d3a40b51900/02a0d11560fcdafbcd7f57a4e74e6df823216e72eeb8d938f5b3a6cd31d9f4787a/Secp256k1/veriKey/hex`

---

Note: Unsure how the additional metadata in the Verida `id` (`?context=0x84e5fb4eb5c3f53d8506e7085dfbb0ef333c5f7d0769bcaf4ca2dc0ca4698fd4#sign`) is captured. @ITStar10 will start implementing now and see how he goes.

**Comment by pranavburnwal** [comment]
Ref: https://github.com/verida/verida-js/issues/210#issuecomment-1188737772
