### ISSUE TITLE
did-client will use vda-did-resolver and vda-did to read and write DID Document objects.

### ISSUE THREAD

**Issue by pranavburnwal** [verida/verida-js#220]
did-client will use vda-did-resolver and vda-did to read and write DID Document objects.

**Comment by pranavburnwal** [comment]
Reference #210 #213

**Comment by tahpot** [comment]
Completed by @ITStar10.

Not yet in PR.

**Comment by pranavburnwal** [comment]
Its already added PR, to be Merged with #211
