### ISSUE TITLE
Update vda-did-resolver to suppport context-hash in attributes

### ISSUE THREAD

**Issue by ITStar10** [verida/verida-js#222]
Original did-resolver library doesn't support context-hashes in the id of attribute items.
Example attribute resolved by original did-resolver:
```
{
  "id": "did:ethr:0xf3beac30c498d9e26865f34fcaa57dbb935b0d74#delegate-1",
  "type": "...",
  "controller": "...",
  "publicKeyHex": "..."
}
```
'did-document's of Verida has context hashes in the id field:
```
{
  "id": "did:ethr:0xf3beac30c498d9e26865f34fcaa57dbb935b0d74?context=0x12...F",
  "type": "...",
  "controller": "...",
  "publicKeyHex": "..."
}
```
Update resolver to support this context.

**Comment by pranavburnwal** [comment]
The is done, to be closed with PR #211
