### ISSUE TITLE
[encryption-utils] Upgrade the signData() function to sign Hex values properly

### ISSUE THREAD

**Issue by pranavburnwal** [verida/verida-js#223]
What doesnt work:
https://github.com/verida/verida-js/blob/main/packages/encryption-utils/src/index.ts#L109

to sign data passed in as Hexadecimal values(eg hashes)

What works:
https://github.com/pubkey/eth-crypto/blob/master/src/sign.js

Reference comment from NONA:
https://github.com/verida/private-data-bridge/blob/main/packages/ethereum/tests/data-signing-options.test.js#L67

**Comment by ITStar10** [comment]
![image](https://user-images.githubusercontent.com/15656252/184074948-10f2e2f4-af62-4bb2-80d5-86c98d89336e.png)
Test results of verida-js packages with updated EncryptionUtils.

I think, remaining issues is not from EncryptionUtils.

**Comment by tahpot** [comment]
@ITStar10 Great. I agree, the other issues were pre-existing so you can ignore.
