### ISSUE TITLE
[proposal] use a signer function instead of a signing key for `VdaDid`

### ISSUE THREAD

**Issue by mirceanis** [verida/verida-js#286]
## Problem

* The requirement to provide the signing key material to work with a `did:vda` prevents it from being used with other wallet constructs.
* It also lessens security for the user since the signing key needs to be available in the same runtime where `VdaDid` is instantiated. This means that it's not possible to transition to more secure key management implementations, that don't export the private key, such as Hardware Security Modules or systems where signatures are computed using multi-party computation.

## Solution

It would be great if key management could be decoupled form the `VdaDid` API.

To be able to do this, the `signingKey` parameter of the `VdaDidConfigurationOptions` should be replaced with a `signer` parameter, like so:

```ts
export interface VdaDidConfigurationOptions {
    identifier: string;
    signer: (data: Uint8Array) => Promise<Uint8Array>;
    chainNameOrId?: string | number;
    callType: Web3CallType;
    web3Options: VeridaWeb3ConfigurationOptions;
}
```

## Adoption

For applications that already have access to the private key, such a signer can be constructed with a function like this:
```ts
function constructSigner(privateKey: Uint8Array) {
  const signer = (data: any) => { return EncryptionUtils.signData(data, <Uint8Array> privateKey); };
  return signer;
}
```

### Details

This line prevents the use of a signing function:
https://github.com/verida/verida-js/blob/01ac4f3f968a8e252d74ee42b45e3397504328ac/packages/vda-did/src/vdaDid.ts#L46

It is constrained by this implementation:
https://github.com/verida/verida-js/blob/01ac4f3f968a8e252d74ee42b45e3397504328ac/packages/did-document/src/did-document.ts#L328

**Comment by tahpot** [comment]
Thanks @mirceanis, that's a great suggestion and pattern.
