### ISSUE TITLE
[bug] EncryptionUtils is signing the wrong data when given a `Buffer`

### ISSUE THREAD

**Issue by mirceanis** [verida/verida-js#287]
## Problem

`EncryptionUtils.signData()` accepts a data parameter as `any` type, and tries to convert it to a string if it's an `object`.
The string is then serialized to a Uint8Array for hashing and signing.
This API is very convenient, as users don't need to worry about the serialization to raw bytes (that much).

Normally, this works without a problem, but some `object` types would produce the wrong raw data to be signed, since they already represent raw data.

Examples:
```ts
let b = new Buffer([1, 2, 3])
// <Buffer 01 02 03>

typeof b === 'object'
// true

let serialized = JSON.stringify(b)
//'{"type":"Buffer","data":[1,2,3]}'

let rawData = Buffer.from(serialized)
// <Buffer 7b 22 74 79 70 65 22 3a 22 42 75 66 66 65 72 22 2c 22 64 61 74 61 22 3a 5b 31 2c 32 2c 33 5d 7d>
// this is not the same as the original 3 byte buffer <Buffer 01 02 03>
```

Something similar happens when `data` is a `Uint8Array`.

## Solution

If the same API needs to be kept, some extra checks need to be made on the `data` before checking for `object`:
```ts
if ( data instanceof Uint8Array) ( // this also covers `Buffer`
  data = utils.hexlify(data) // the hashing method that follows also tries to serialize strings, except when they are hex strings
} else if ( typeof data === 'object') {
  data = JSON.stringify(data)
}
```

## Details

https://github.com/verida/verida-js/blob/01ac4f3f968a8e252d74ee42b45e3397504328ac/packages/encryption-utils/src/index.ts#L110

**Comment by tahpot** [comment]
Thanks @mirceanis -- that's a really great pickup!

**Comment by tahpot** [comment]
Resolved with https://github.com/verida/verida-js/commit/5416ca0e30706f481563969e34589a88ea5e4058
