### ISSUE TITLE
[all] Check test codes running for all packages & update

### ISSUE THREAD

**Issue by ITStar10** [verida/verida-js#297]
Check for packages that use the Verification

**Comment by tahpot** [comment]
@ITStar10 is working through all the unit tests in all `verida-js` repos to confirm they all pass.

@ITStar10 to update this issue with any that fail and need to be reviewed @tahpot.

**Comment by tahpot** [comment]
Packages needing review by @tahpot:

- [ ] `client-ts`
- [ ] `account-node`
- [ ] `storage-link`
- [x] `verifiable-credentials` (@ITStar10 to check)
