### ISSUE TITLE
Remove JSON.stringify global scope hot replacement with `json.sortify`

### ISSUE THREAD

**Issue by Eengineer1** [verida/verida-js#343]
Hello everybody,

The aforementioned [issue](https://github.com/verida/verida-js/blob/c94b95de687c64cc776652602665bb45a327dfb6/packages/encryption-utils/src/index.ts#L10).

For context:

This technique renders the deterministic nature of JSON.stringify unusable, since keys are not preserved, rather than sorted alphabetically.

Having that in mind, the issue is that the hot replacement is done in global scope, i.e. importing a module that utilises the encryption-utils declarations _or_ bundling altogether is sufficient to accidentally end up with non-deterministic behaviour.

An example is:

- Deserialising a string to a struct / object.
- Process / alter state.
- Serialise + sort object keys by default. <-- Point of non-deterministic outcome, if integrity hashes are in place and / or JSON hashing <> buffer conversion is in place.

Suggestion:

I'd suggest swapping out + enhancing the global JSON object with a `sortify` method and / or serialising + sorting in 2 distinct steps.
Otherwise, a simple utility function could be sufficient, depending on you internal usage of key sorting on serialisation.

Let us know your thoughts.

**Comment by tahpot** [comment]
Thanks for the great bug report @Eengineer1.

This sorted JSON is required to ensure signatures are deterministic when stored in the Verida database, however as you rightly point out, it should be limited to the Verida library and not global.

This PR is pending testing and review which will prioritize tomorrow:

https://github.com/verida/verida-js/pull/345
