### ISSUE TITLE
The Verida Connect modal is not cleaned from the DOM and can even be added multiple times

### ISSUE THREAD

**Issue by aurelticot** [verida/verida-js#371]
The Verida Connect modal is injected in the DOM when a connection is triggered. Whether the connection goes through or not, the elements are not cleaned from the DOM. If a connection is triggered again, the modal is added again.

There is no apparent conflict but it's not optimised and clean.

<img width="544" alt="Screenshot 2023-12-01 at 2 13 59 pm" src="https://github.com/verida/verida-js/assets/61808169/e0fedde7-adfc-467e-81e8-8fd6d46cb339">

**Comment by tahpot** [comment]
Fixed with https://github.com/verida/verida-js/commit/9c78f295643382995f4d382003873086f25668fe

Prevents duplicate DOM entries, but does leave the existing DOM entry there as it won't do any harm.
