### ISSUE TITLE
Bug: New mainnet account shows testnet label

### ISSUE THREAD

**Issue by pranavburnwal** [verida/verida-js#395]
Hi

Made a fresh mainnet account, it showed testnet on wallet balances page.
Attaching a video to showcase. https://github.com/verida/verida-js/assets/15976005/82ae4882-1a7c-427d-882c-9ce988b6f767

Thanks!
Pranav

**Comment by aurelticot** [comment]
Thanks for the feedback @pranavburnwal.
When we enabled the Verida Mainnet, the crypto wallet feature was still using the Testnet blockchains only.
We enabled the blockchain mainnets a few weeks later with the version `1.1.0` of the Verida Wallet.
