### ISSUE TITLE
Update all demos to use client-ts

### ISSUE THREAD

**Issue by tahpot** [verida/verida-js#5]
Update all demos to use the new Verida `client-ts` package:

- [ ] https://github.com/verida/markdown-notes-demo
- [ ] https://github.com/verida/generic-demo
- [ ] https://github.com/verida/vault-auth-client-demo
- [ ] https://github.com/verida/practitioner-erm-web
- [ ] https://github.com/verida/credential-scanner-web
- [ ] https://github.com/verida/verida-health-credential-management
- [ ] https://github.com/verida/vuejs-template

Depends on #1

**Comment by nick-verida** [comment]
* markdown-notes-demo done
* generic-demo done. Need to deprecate this project
* vault-auth-client-demo. Covered by tech capabilities

practitioner-erm-web - not sure
credential-scanner-web - not sure
verida-health-credential-management - is this the one Saad is updating?
vuejs-template - not sure

**Comment by nick-verida** [comment]
@tahpot can you clarify which projects still need updating. 

Also how do we deprecate demos we aren't updating? Put "deprecated" in the name or something?

**Comment by nick-verida** [comment]
This is all done

**Comment by tahpot** [comment]
@ysam21 Why was this reopened?
