### ISSUE TITLE
Datastore validation of emails doesn't work

### ISSUE THREAD

**Issue by tahpot** [verida/verida-js#51]
This was identified in the `web-sandbox`.

**Comment by tahpot** [comment]
Added failed unit test to demonstrate the issue: https://github.com/verida/verida-js/tree/bug/51-email-validation-fails

Investigate an issue with the `ajv JSON validation library?

Required fields validation is working correctly.

**Comment by kalanamt** [comment]
Estimation :- 48 hrs
