### ISSUE TITLE
Export default class  name correctly 

### ISSUE THREAD

**Issue by cmcWebCode40** [verida/verida-js#84]
For  the Class names to be displayed in the Classes section as shown in this screenshot,
default classes have to be exported like e.g

<img width="695" alt="Screenshot 2021-10-26 at 23 04 43" src="https://user-images.githubusercontent.com/54280620/138970517-8016f49c-85a9-4ddb-913b-833cb0fb9a8f.png">

```js
class Client {
.....
}

export default Client;
```

But most default classes were exported like this  e.g

```js
export default class Client {
.....
}
```
thats why is showing as exports in the Classes section.

**Comment by tahpot** [comment]
@cmcWebCode40 Did you change these or do I need to?

**Comment by cmcWebCode40** [comment]
I did change it correctly

**Comment by tahpot** [comment]
@cmcWebCode40 Got it, thanks.

Are you able to update PR #85 so it can be merged in?

**Comment by cmcWebCode40** [comment]
@tahpot, I haven't 

is it of a high priority now so I can resolve the merge conflicts then notify you today?

**Comment by cmcWebCode40** [comment]
Hi @tahpot, 
I have updated this branch with the changes from `main` and also resolved all merge conflicts
